// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkf7MZtMCJ6-8XFAEaFYvnG79bFNTYQAE',
    appId: '1:709917300699:web:8b5cd28143aad2499a79fe',
    messagingSenderId: '709917300699',
    projectId: 'speak-dine-1a95b',
    authDomain: 'speak-dine-1a95b.firebaseapp.com',
    storageBucket: 'speak-dine-1a95b.firebasestorage.app',
    measurementId: 'G-MJ892M5WP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx8-2gjmCADQKL-RxNHhRrFZ_DLStG_wM',
    appId: '1:709917300699:android:c254282978d0a46f9a79fe',
    messagingSenderId: '709917300699',
    projectId: 'speak-dine-1a95b',
    storageBucket: 'speak-dine-1a95b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIgmb0WCxv52ErrqNArXDnY6l9Qq9ulkE',
    appId: '1:709917300699:ios:6a21f807c29bcd3e9a79fe',
    messagingSenderId: '709917300699',
    projectId: 'speak-dine-1a95b',
    storageBucket: 'speak-dine-1a95b.firebasestorage.app',
    iosClientId: '709917300699-iaqrj50fgr7916u8hjo8i3g9cnqnpua1.apps.googleusercontent.com',
    iosBundleId: 'com.speakdine.app.speakdineApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIgmb0WCxv52ErrqNArXDnY6l9Qq9ulkE',
    appId: '1:709917300699:ios:6a21f807c29bcd3e9a79fe',
    messagingSenderId: '709917300699',
    projectId: 'speak-dine-1a95b',
    storageBucket: 'speak-dine-1a95b.firebasestorage.app',
    iosClientId: '709917300699-iaqrj50fgr7916u8hjo8i3g9cnqnpua1.apps.googleusercontent.com',
    iosBundleId: 'com.speakdine.app.speakdineApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkf7MZtMCJ6-8XFAEaFYvnG79bFNTYQAE',
    appId: '1:709917300699:web:f3faaebbbde3ce579a79fe',
    messagingSenderId: '709917300699',
    projectId: 'speak-dine-1a95b',
    authDomain: 'speak-dine-1a95b.firebaseapp.com',
    storageBucket: 'speak-dine-1a95b.firebasestorage.app',
    measurementId: 'G-WS0ETEQ6X3',
  );

}