// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhUpLZwaaacW6Q0dH2-hVpXBW8zUusiio',
    appId: '1:646135588641:web:b5a5e7bbe72cc306718060',
    messagingSenderId: '646135588641',
    projectId: 'speakdineapp',
    authDomain: 'speakdineapp.firebaseapp.com',
    storageBucket: 'speakdineapp.firebasestorage.app',
    measurementId: 'G-J19E73WFZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc1YKB0yv8-ceJksikYKCkHNI_G-PatXk',
    appId: '1:646135588641:android:71810be62894ab19718060',
    messagingSenderId: '646135588641',
    projectId: 'speakdineapp',
    storageBucket: 'speakdineapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxqj-kQDxiLJMSo1AXbO4Uq9Mlt5LT2pg',
    appId: '1:646135588641:ios:d045470a8c2cae35718060',
    messagingSenderId: '646135588641',
    projectId: 'speakdineapp',
    storageBucket: 'speakdineapp.firebasestorage.app',
    iosBundleId: 'com.speakdine.app.speakdineApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxqj-kQDxiLJMSo1AXbO4Uq9Mlt5LT2pg',
    appId: '1:646135588641:ios:d045470a8c2cae35718060',
    messagingSenderId: '646135588641',
    projectId: 'speakdineapp',
    storageBucket: 'speakdineapp.firebasestorage.app',
    iosBundleId: 'com.speakdine.app.speakdineApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhUpLZwaaacW6Q0dH2-hVpXBW8zUusiio',
    appId: '1:646135588641:web:b55a7ade5bf3843a718060',
    messagingSenderId: '646135588641',
    projectId: 'speakdineapp',
    authDomain: 'speakdineapp.firebaseapp.com',
    storageBucket: 'speakdineapp.firebasestorage.app',
    measurementId: 'G-NJ53LQFE2D',
  );
}
